### ISSUE TITLE
Implement unit tests for a search problem with actions

### ISSUE THREAD

**Issue by gonzalezsieira** [citiususc/hipster#142]
Current tests for optimal searh problems are implemented taking as basis the Romanian problem, which does not include explicit actions for moving between states.

This is a limitation for testing functions depending on actions, and a test for a problem with explicit actions defined should be implemented to solve this.

**Comment by kwahsog** [comment]
Hi,

Looking to resolve this issue, but I am slightly confused as to the desired unit tests to implement. The current unit tests are using the Romanian problem and testing that the optimal route between Arad and Bucharest is produced. Could you please eloborate on what you mean by a test with explicit actions? 

Would it be suitable to implement tests for a series of explicit routes between adjacent states and compare them to the single route between the states? 

Thanks.

**Comment by sjhacoder** [comment]
Hi,
Is this still up for grabs? I am interested in working on this one. Can I get an example please, to better understand the requirements ?

**Comment by umangsehgal** [comment]
@gonzalezsieira  @pablormier: Is this issue still up for grabs?

**Comment by pablormier** [comment]
Dear @umangsehgal, @sjhacoder 

Unfortunately, due to other responsibilities, work, etc, we cannot guarantee that we will have time to review contributions. We still mantain hipster4j but mostly for basic maintenance and important bugfixes. I will remove the up for grabs tags.

Thank you so much for your interest anyway!
