### ISSUE TITLE
Only given one solution when running AStar or Dijkstra?

### ISSUE THREAD

**Issue by goose2460** [citiususc/hipster#153]
I'm only getting one solution when running a search using the following graph:

			graphBuilder.connect((long) 6).to((long) 7);
			graphBuilder.connect((long) 7).to((long) 10);
			graphBuilder.connect((long) 6).to((long) 8);
			graphBuilder.connect((long) 8).to((long) 10);
			graphBuilder.connect((long) 6).to((long) 9);
			graphBuilder.connect((long) 9).to((long) 10);

When I search this, the only solution I'm getting is (6,7,10).  I would like to also see the (6,8,10) and (6,9,10) solutions.  Can anyone offer some guidance?

**Comment by pablormier** [comment]
Hi @goose2460. Equivalent paths are automatically discarded for efficiency reasons. But in some cases it would be interesting to be able to count all paths. We'll consider this feature for v1.0.0

**Comment by gonzalezsieira** [comment]
As @pablormier said, we'll take a look to make an efficient implementation of this for future releases. Thanks for your contribution!
