### ISSUE TITLE
Implementation of Annealing localsearch

### ISSUE THREAD

**Issue by michaelhaaf** [citiususc/hipster#158]
As a user, I would like an implementation of an annealing local search algorithm so that I can avoid the local minima problem of the hill climbing local search algorithm.

Link: https://en.wikipedia.org/wiki/Simulated_annealing

**Comment by gonzalezsieira** [comment]
Closed in 893ca3b2d85976501f41a9e5625bc97dc8a5ec18 . Thanks for your contribution!
