### ISSUE TITLE
Write undirected graph to json (and read it back again)

### ISSUE THREAD

**Issue by damianflannery** [citiususc/hipster#172]
Hi, thanks for creating this library. 

I'm looking to use this for an Android project and wondered is there an easy way to serialise/persist a graph to a standard format (like graphjson) and read it back again?

Or do I have to roll my own?

Thanks,
Damian

**Comment by pablormier** [comment]
Hi @damianflannery, thanks for using the library.

Here you have an example where we use the old TinkerPop Blueprints API to read a graphml file https://github.com/citiususc/hipster/wiki/Multiobjective-Search-with-Hipster-and-TinkerPop-Blueprints

You can also use http://tinkerpop.apache.org to read from/to a JSON file and then adapt the Graph interface of TinkerPop to be used as a HipsterGraph. In the current implementation we have some classes to adapt from a TinkerPop graph to a HipsterGraph, take a look at this https://github.com/citiususc/hipster/blob/1.0.X/hipster-third-party-graphs/src/main/java/es/usc/citius/hipster/thirdparty/graphs/blueprints/BlueprintsHipsterGraphAdapter.java

Still, if you find some difficulties with this, please don't hesitate to ask us.

Cheers,
Pablo

**Comment by damianflannery** [comment]
That's great Pablo, many thanks for your help!
