### ISSUE TITLE
Difference between FibonacciHeap implementations

### ISSUE THREAD

**Issue by nikolauskrismer** [citiususc/hipster#176]
I just noticed that hipster offered two different implementations for a FibonacciHeap some time ago.

One is implemented by Keith Schwarz from Stanford (FibonacciHeap.java; the implementation is still used in the current master version) while the other one was based on Nathan Fiedlers implementation (https://github.com/citiususc/hipster/blob/5aca4c2abe848f799b32be5f377c9c2fc0df27b3/src/main/java/es/usc/citius/lab/hipster/collection/JGraphTFibonacciHeap.java).

Is there a special reason why the last one was removed?
Was it due to lacking performance or because of license issues?

I am looking into fibonacci heap performance right now and it would be great if you could give me some insights. Besides http://nlfiedler.github.io/2008/05/31/analysis-of-java-implementations-of-fibonacci-heap.html I did not find much useful regarding fibonacci Heap performance in Java

**Comment by gonzalezsieira** [comment]
Hi @nikolauskrismer . Can't remember right now if we did any benchmark, but It seemed to be a license issue, because the code of Nathan Fiedlers is licensed GPL 2.1 and it is not compatible with Apache 2.0.

Thanks for your interest,
