### ISSUE TITLE
Bug in method charToPoint() 

### ISSUE THREAD

**Issue by ElKroketto** [citiususc/hipster#179]
There's a bug in class package es.usc.citius.hipster.util.examples.maze.Maze2D on line 125:

for(int column = 0; **row < this.columns**; column++){`

I guess the threshold should be `colum  < this.columns`

**Comment by anuragster** [comment]
I am taking up this issue.

**Comment by gonzalezsieira** [comment]
Hi @anuragster , I've jus merged your pull request. Thanks for your contribution!
