### ISSUE TITLE
New contributions

### ISSUE THREAD

**Issue by font44** [citiususc/hipster#183]
Hi,
I am interested in making some significant contributions to this project because I am excited by its problem domain. Can you please suggest something complex that I can take a look at it? I'd be happy to discuss my approach with you before starting to code.

Thanks.

**Comment by adityasrini** [comment]
On a similar vein, I’m interested in this but as a beginner would be interested in more *simpler* solutions or bug fixes before I attempt the more complex ones! The “up for grabs” label has closed all issues and I wonder if there are no other smaller problems to solve.

**Comment by gonzalezsieira** [comment]
Hi @kvijayva and @adityasrini. Thanks for your interest in developing hipster4j. Unfortunately at this time we are no actively working on further improvements. This project is still maintained, but only for bugfixes.

Regards,
