### ISSUE TITLE
Replanning / dynamic graph within AD*?

### ISSUE THREAD

**Issue by martypitt** [citiususc/hipster#184]
Hi

I see a number of [open issues](https://github.com/citiususc/hipster/issues?utf8=%E2%9C%93&q=ad*) regarding replanning in AD*.  Does this currently work?

Also, forgive a newb question, but when building a search problem using the `Wizard`, how do I advise change of state to the graph?

**Comment by gonzalezsieira** [comment]
Hi @martypitt : 

Current implementation of `ADStarForward` is supposed to be complete according to [the algorithm description](https://pdfs.semanticscholar.org/742c/73647b2e4e8ea6e0c03910bc9cb5a168d10c.pdf) . Unfortunately there are no tests for replanning (yet) so I cannot guarantee it's 100% functional. 

However, I tested the anytime search part, which relies on the same the code (Fig. 2 of the link, lines 17-23) and it's functional, so I would say it's worth giving it a try. 

Regarding to your question, after you have an instance of `ADStarForward.Iterator` you can indicate the algorithm that some arc costs have changed and need to be re-evaluated with the method `addTransitionsChanged(Collection<Transition<A, S>> transitions)`. There is no other way to do so at the moment.

Please, let us know if you detect some unexpected behaviour while replanning.

Best regards,
